name: reslate
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.0
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.8.4
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.2
  form_field_validator: ^1.1.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  http: ^0.13.6
  shared_preferences: ^2.2.0
  translator: ^0.1.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
